import { pathSchema, readQuery, checkoutQuery, discountCreate, discountUpdate, customerCreate, customerUpdate, productCreate, productUpdate } from "./schemas.js";

const frontend = "https://admin.easystore.co/assets/index-WRCYpubE.js";
const read = (id, path, description, parameter) => ({
  id, method: "GET", path: `/admin/v2/store${path}`, description, enabled: true, source: frontend,
  ...(parameter ? { pathSchema: pathSchema(parameter) } : {}), querySchema: readQuery,
});

// Add explicit routes here and shared argument schemas in schemas.js.
export default [
  {
    id: "list_abandoned_checkouts",
    method: "GET",
    path: "/admin/v2/store/checkouts",
    description: "List abandoned checkouts. One page per call; inspect upstream params.page_count for pagination.",
    enabled: true,
    source: "scripts/easystore_admin_checkouts.py",
    querySchema: checkoutQuery,
    queryDefaults: {"page": 1, "limit": 50, "start_date": "", "end_date": "", "sort": "created_at.desc"},
  },
  {
    id: "list_themes",
    method: "GET",
    path: "/admin/v2/store/themes",
    description: "List store themes.",
    enabled: true,
    source: "docs/EASYSTORE_API_DEPLOYMENT.md",
  },
  read("list_products", "/products", "List products. One page per call."),
  read("get_product", "/products/{product_id}", "Retrieve one product.", "product_id"),
  read("list_customers", "/customers", "List customers. One page per call."),
  read("get_customer", "/customers/{customer_id}", "Retrieve one customer.", "customer_id"),
  read("list_orders", "/orders", "List orders. One page per call."),
  read("get_order", "/orders/{order_id}", "Retrieve one order.", "order_id"),
  read("list_collections", "/collections", "List collections. One page per call."),
  read("get_collection", "/collections/{collection_id}", "Retrieve one collection.", "collection_id"),
  read("list_locations", "/locations", "List locations. One page per call."),
  read("get_location", "/locations/{location_id}", "Retrieve one location.", "location_id"),
  read("list_stock_adjustments", "/stock_adjustments", "List stock adjustments. One page per call."),
  read("get_stock_adjustment", "/stock_adjustments/{stock_adjustment_id}", "Retrieve one stock adjustment.", "stock_adjustment_id"),
  read("list_purchase_orders", "/purchase_orders", "List purchase orders. One page per call."),
  read("get_purchase_order", "/purchase_orders/{purchase_order_id}", "Retrieve one purchase order.", "purchase_order_id"),
  read("list_inventory_transfers", "/inventory_transfers", "List inventory transfers. One page per call."),
  read("get_inventory_transfer", "/inventory_transfers/{inventory_transfer_id}", "Retrieve one inventory transfer.", "inventory_transfer_id"),
  read("list_discounts", "/discounts", "List discounts. One page per call."),
  read("get_discount", "/discounts/{discount_id}", "Retrieve one discount.", "discount_id"),
  read("list_discounts_new", "/discounts/list", "List discounts new."),
  read("list_vouchers", "/vouchers/list", "List vouchers."),
  read("list_voucher_campaigns", "/voucher_campaigns", "List voucher campaigns."),
  read("list_inventory_levels", "/inventory_levels", "List inventory levels."),
  read("get_inventory_level", "/inventory_level", "Get inventory level."),
  read("get_general_settings", "/settings/general", "Get general settings."),
  read("list_enabled_channels", "/enabled-channels", "List enabled channels."),
  read("list_store_users", "/users", "List store users."),
  read("get_store_global", "/global", "Get store global."),
  read("list_discount_usages", "/discounts/{discount_id}/usages", "List discount usages.", "discount_id"),
  read("list_discount_setting_logs", "/discounts/{discount_id}/setting_logs", "List discount setting logs.", "discount_id"),
  read("get_discount_visual_settings", "/discounts/visual_settings", "Get discount visual settings."),
  read("list_discount_redemption_logs", "/discounts/codes/{discount_id}", "List discount redemption logs.", "discount_id"),
  read("list_customer_vouchers", "/customers/{customer_id}/vouchers", "List customer vouchers.", "customer_id"),
  read("list_customer_addresses", "/customers/{customer_id}/addresses", "List customer addresses.", "customer_id"),
  read("get_customer_membership", "/customers/{customer_id}/membership", "Get customer membership.", "customer_id"),
  read("list_order_fulfillments", "/orders/{order_id}/fulfillments", "List order fulfillments.", "order_id"),
  read("get_product_variants", "/products/{product_id}/variants", "Get product variants.", "product_id"),
  read("list_stock_adjustment_items", "/stock_adjustments/{adjustment_id}/items", "List stock adjustment items.", "adjustment_id"),
  {
    id: "create_discount",
    method: "POST",
    path: "/admin/v2/store/discounts",
    description: "Create a promotion/discount or voucher definition. This is the editor createDiscount endpoint; POST /vouchers is a listing operation, not voucher creation.",
    enabled: true,
    source: frontend,
    bodySchema: discountCreate,
    bodyDefaults: {"id": 0, "description": "", "prerequisite_quantity_range": null, "prerequisite_subtotal_range": null, "prerequisite_order_ids": null, "prerequisite_product_ids": "all", "prerequisite_variant_ids": null, "prerequisite_collection_ids": null, "entitled_quantity": 0, "value_limit": 0, "entitled_regions": {"countries": []}, "entitled_country_ids": null, "prerequisite_location_ids": null, "prerequisite_locations": [], "entitled_product_ids": "all", "entitled_variant_ids": null, "entitled_collection_ids": null, "prerequisite_exclusion_variant_ids": [], "entitled_exclusion_variant_ids": [], "allocation_limit": 1, "ends_at": "", "discount_codes": null, "redemption_setting": null, "customer_selection": "all", "prerequisite_group_ids": [], "prerequisite_bir_citizen_group_ids": [], "prerequisite_customer_ids": [], "prerequisite_membership_tier_ids": [], "campaign_page_ids": [], "usage_limit": 0, "usage_limit_per_customer": 0, "is_show_in_voucher_shop": true},
  },
  {
    id: "update_discount",
    method: "PUT",
    path: "/admin/v2/store/discounts",
    description: "Update a promotion using its id in the JSON body. Inspect get_discount first; send only fields allowed by this schema.",
    enabled: true,
    source: frontend,
    bodySchema: discountUpdate,
  },
  {
    id: "enable_discounts",
    method: "PUT",
    path: "/admin/v2/store/discounts/bulk_enable",
    description: "Enable the comma-separated discount IDs.",
    enabled: true,
    source: frontend,
    bodySchema: {"type": "object", "properties": {"discount_ids": {"type": "string", "pattern": "^\\d+(,\\d+)*$", "maxLength": 4096}}, "required": ["discount_ids"], "additionalProperties": false},
  },
  {
    id: "disable_discounts",
    method: "PUT",
    path: "/admin/v2/store/discounts/bulk_disable",
    description: "Disable the comma-separated discount IDs.",
    enabled: true,
    source: frontend,
    bodySchema: {"type": "object", "properties": {"discount_ids": {"type": "string", "pattern": "^\\d+(,\\d+)*$", "maxLength": 4096}}, "required": ["discount_ids"], "additionalProperties": false},
  },
  {
    id: "delete_discount",
    method: "DELETE",
    path: "/admin/v2/store/discounts",
    description: "Delete a promotion. EasyStore admin DELETE uses query parameters, not a JSON body.",
    enabled: true,
    source: frontend,
    querySchema: {"type": "object", "properties": {"id": {"anyOf": [{"type": "integer", "minimum": 1}, {"type": "string", "pattern": "^[A-Za-z0-9_-]{1,128}$"}]}}, "required": ["id"], "additionalProperties": false},
  },
  {
    id: "delete_discounts",
    method: "DELETE",
    path: "/admin/v2/store/discounts/bulk_delete",
    description: "Delete the specified promotion IDs using query parameters.",
    enabled: true,
    source: frontend,
    querySchema: {"type": "object", "properties": {"discount_ids": {"type": "string", "pattern": "^\\d+(,\\d+)*$", "maxLength": 4096}}, "required": ["discount_ids"], "additionalProperties": false},
  },
  {
    id: "delete_products",
    method: "DELETE",
    path: "/admin/v2/store/products",
    description: "Delete the specified product IDs using query parameters.",
    enabled: true,
    source: frontend,
    querySchema: {"type": "object", "properties": {"product_ids": {"type": "string", "pattern": "^\\d+(,\\d+)*$", "maxLength": 4096}}, "required": ["product_ids"], "additionalProperties": false},
  },
  {
    id: "create_customer",
    method: "POST",
    path: "/admin/v2/store/customers",
    description: "Create a customer using the flat admin customer JSON payload. The upstream store enforces configured identity requirements.",
    enabled: true,
    source: "https://admin.easystore.co/assets/index-DhhWi_BX.js; https://admin.easystore.co/assets/index-WRCYpubE.js",
    bodySchema: customerCreate,
  },
  {
    id: "update_customer",
    method: "PUT",
    path: "/admin/v2/store/customers/{customer_id}",
    description: "Update a customer using the flat admin customer JSON payload. The upstream store enforces configured identity requirements.",
    enabled: true,
    source: "https://admin.easystore.co/assets/index-DhhWi_BX.js; https://admin.easystore.co/assets/index-WRCYpubE.js",
    bodySchema: customerUpdate,
    pathSchema: pathSchema("customer_id"),
  },
  {
    id: "create_product",
    method: "POST",
    path: "/admin/v2/store/products",
    description: "Create a product using the flat admin editor payload. Explicitly choose publication state, tax, shipping, inventory, and variants. Product update id in body must match path product_id.",
    enabled: true,
    source: "https://admin.easystore.co/assets/index-C_eQG1LX.js; https://admin.easystore.co/assets/index-WRCYpubE.js",
    bodySchema: productCreate,
  },
  {
    id: "update_product",
    method: "PUT",
    path: "/admin/v2/store/products/{product_id}",
    description: "Update a product using the flat admin editor payload. Explicitly choose publication state, tax, shipping, inventory, and variants. Product update id in body must match path product_id.",
    enabled: true,
    source: "https://admin.easystore.co/assets/index-C_eQG1LX.js; https://admin.easystore.co/assets/index-WRCYpubE.js",
    bodySchema: productUpdate,
    pathSchema: pathSchema("product_id"),
  },
  {
    id: "update_product_positions",
    method: "PATCH",
    path: "/admin/v2/store/products/positions",
    description: "Replace the full product display order. product_ids must be the complete desired top-to-bottom order; inspect list_products sorted by position before changing it.",
    enabled: true,
    source: "ADMIN_API_EVIDENCE.md",
    bodySchema: {
      type: "object",
      properties: {
        product_ids: {
          type: "array",
          minItems: 1,
          uniqueItems: true,
          items: { type: "integer", minimum: 1 },
        },
      },
      required: ["product_ids"],
      additionalProperties: false,
    },
  },
];
